### ISSUE TITLE
ORCA4.8関連

### ISSUE THREAD

**Issue by KatouBuntarou** [KatouBuntarou/OpenDolphin-2.3mh#83]
ORCA4.8との連携評価メモです。

○ ORCAの外来受付をOpenDolphinで取得OK。
○ ORCA・OpenDolphinの両方のDBをPostgreSQL9.3上で動作させているが、
　 DBを共存させること自体には問題なさそう。

× OpenDolphinから診療行為をORCAに送信してもORCAで拾えていない？
　/var/log/syslogにエラーログあり。
　調査中。
× OpenDolphinから病名をORCAに送信してもORCAで拾えていない？
　/var/log/syslogにエラーログあり。
　調査中。

**Comment by KunitoishiTomii** [comment]
OSC対応あり
$ sudo apt-get install -y jma-receipt
のあと
$ wget https://ftp.orca.med.or.jp/pub/data/receipt/outline/update/claim_update.tar.gz
$ tar xvzf claim_update.tar.gz
$ sudo bash claim_update.sh
でORCA4.8でもうまくいっている様子です。

**Comment by MasudaNaika** [comment]
ありがとうございます。
当方、OSCから2014/12/22にclaim_update.tar.gzを頂いて、12/23にOSCに動作検証の報告をしています。
まだORCA 4.8のパッチに含まれてないですねぇ…

**Comment by KunitoishiTomii** [comment]
動作検証ありがとうございます。
今のところ（当分の間？）は手動で入れてくださいということですね。
普通のインストールマニュアルの方もコマンドで入れるようになってましたから。
いつもありがとうございます。

**Comment by MasudaNaika** [comment]
あ、ほんとだ、マニュアル追記されてますね。
http://www.orca.med.or.jp/receipt/download/trusty/trusty_install_48.html#receipt-install

CLAIMのモジュールに不具合があり、プログラム更新で対応できないため、手動で適用する必要があります。
$ wget https://ftp.orca.med.or.jp/pub/data/receipt/outline/update/claim_update.tar.gz
$ tar xvzf claim_update.tar.gz
$ sudo bash claim_update.sh

情報ありがとうございます。

**Comment by KatouBuntarou** [comment]
＞富井先生、増田先生
お世話になります、情報ありがとうございました。
では明後日あたりに当方でも確認し、確認取れ次第本IssueはCloseします。

**Comment by KatouBuntarou** [comment]
遅くなりました。

確かにclaim受信できるようになったこと確認しました。

ただ、サーバ機の再起動直後、jma-receiptのserviceを一度restartしないとclaim serverが立ち上がらないような……？
どなたか、同じ症状出ている方いらっしゃいますか？ほかにもいらっしゃるようならOSCに問い合わせようかと思うのですが。

**Comment by KunitoishiTomii** [comment]
あらら・・確かに。こちらでも現象確認できました。
再起動時も、ps axでは
/usr/bin/ruby1.9.1 /usr/lib/jma-receipt/scripts/claim/rb/clm_rcv.rb 8210
あるけど・・
受付（送信）はOpenDolphin側に反映されていますが、病名や診療行為（受信）ができてないようです。（エラーが出て、ORCAに反映されない）
service jma-receipt を立ち上げ直すと、見事に病名、診療行為で反映できています。
ORCA起動スクリプトの問題でしょうか？
どうぞよろしくお願いします。

**Comment by KatouBuntarou** [comment]
＞富井先生
ありがとうございます。ではこちらの環境のみの問題ということではなさそうですね。
問い合わせかけてみます。

**Comment by KunitoishiTomii** [comment]
ありがとうございます。
ただ、こちらではCUIのみのインストールで、GUI環境をインストールしておりません。
（本来の公式インストール環境とは違うので）その点、お含みいただけると幸いです。
おそらくそこは関係ないとは思いますが。

**Comment by KatouBuntarou** [comment]
残念ながら当方もUbuntu 14.04Serverなんですよねえ・・・・・・（＾＾；
まあ、そこは触れずに聞いてみようと思います。

**Comment by MasudaNaika** [comment]
うちもserver...
問い合わせよろしくお願いします

**Comment by KatouBuntarou** [comment]
OSCに問い合わせました。

OSC側でも現象再現を確認し、現在調査中とのこと。
ひとまずは、ORCA4.8を用いる場合は sudo service jma-receipt restart を実行するようお願いします、とのことでした。

とはいえ当院はまだしばらくは4.7使用ですが（＾＾；
本件解決したら4.8に移行しようかなと考え中。

**Comment by KunitoishiTomii** [comment]
早速のお問い合わせありがとうございました。
当院もテストはしつつ、本番環境は移行待機しておきます。^_^;

**Comment by KatouBuntarou** [comment]
OSCより返信あり、試験用アップデートモジュールを頂いたので、評価実施しました。
期待通り、サーバ再起動直後でもclaim受信可能であることを確認し、OSCに返信済です。

今のところ、まだ公式展開はされていない模様。
公式展開を確認し次第、本IssueをCloseする予定です。

**Comment by MasudaNaika** [comment]
ありがとうございました

**Comment by KunitoishiTomii** [comment]
ありがとうございます。

**Comment by KatouBuntarou** [comment]
ORCA-ANNOUNCE:03579にて、再起動直後にclaim受信が不可能となる事象の改善がアナウンスされています。
ソースコード確認したところ、当初評価した部分の修正を確認したため、本IssueはCloseします。

ご協力くださりありがとうございました。

（4.8どうしようかなあ・・・・・・）

**Comment by MasudaNaika** [comment]
ありがとうございました

CLAIM組は肩身が狭いですねぇ…

ORCA APIに一本化するならば、受付情報をpollingで取りにいかないといけなくて、いまさらそんなのヤダし、保険情報がCLAIMと違うフォーマットで、DolphinのHealthInsuranceModelに変換しないといけないのですが、CLAIM保険とAPI保険の対応がイマイチ分からないので、受付CLAIMから卒業できません。ORCA APIが受付POST機能を実装してくれるまでは…

ORCA要望　2012/7/9 20120709-001　これ、私ですが、まだ
【検討中】
 　　　 ,､_,､　 ,､_,､
 　 ,､_('・ω)(ω・`)､_,､
 　('・ω)uﾟ 　ﾟuu(ω・`)
 　 ﾞuuﾟ(　'・) (・`　)uu'
 　　　　ﾟuuﾟ 　ﾟuJﾟ

なんですよ…

各種データの取得はOpenDolphinはもともとPostgresに直接取りに行っており、API使わないほうが、なんでも自分のとりたい情報を高速に取得でますし。

もちろんORCA APIのメリットも分かるのですが。

**Comment by KunitoishiTomii** [comment]
ありがとうございました。
＞受付情報をpollingで取りにいかないといけなくて、いまさらそんなのヤダ
確かに、先祖返りな感じですね。
CLAIMと同等な機能を実装までは、CLAIMフォローしていただくようにお願いします、でいけるでしょうか。
2012/7/9 20120709-001拝見しました、２年以上前に検討中・・きっと中の人足りないってとこ？

**Comment by MasudaNaika** [comment]
Katou san
うちはVMで動かしてるので、移行は気楽ではあるのですが、Dolphin側の不具合はその場で修正しちゃいますが、ORCAがトラブルと手も足も出ませんし…　不具合出しに協力せないかんのですが…

Tomii sensei
たぶん忘れ去られているんだと思います。というか、ほかの誰からも同じ要望がないほうがオドロキ
診療行為送信はAPI、だけど受付はCLAIMって、なんかスッキリせんです。

**Comment by KunitoishiTomii** [comment]
ごもっともです。以前の資料の中に、日レセAPIのデメリット・・
受付完了通知などの日レセ側からのトリガーをリアルタイムに受け取れません。
  (claimは、受付完了等の情報を連携相手システムへ内容を含め通知することが可能です)
とありました。中の人も当分受付のCLAIMは残す方向？でしょうか。スッキリできないですが。

**Comment by skoba** [comment]
来年度はAPIの追加があるようです。
http://www.orca.med.or.jp/receipt/tec/api/haori.html
このAPIだとORCA側から電子カルテ側に受付完了の情報を送ることができるようになっているようです。
さて，CLAIMどうしよう。

**Comment by KunitoishiTomii** [comment]
拝見いたしました。受付情報送信PUSHの優先順位は[2]になっていました。
なるほど、いろいろ少しずつ進んでいるんですね。勉強になります。

**Comment by MasudaNaika** [comment]
skoba sensei
ありがとうございます。HAORIというものが予定されているのですね。
CLAIMは、さて、どうなっていくのでしょうか。ORCAが独自API推しで新規機能追加がAPIのみになっている現状、CLAIMの未来はちょっと厳しいかなぁ。CLAIMの親玉のMMLも、医療情報交換規約としてはカネのパワーかSSMIXのほうが目立つ気がします。

**Comment by KatouBuntarou** [comment]
＞増田先生
うちも不具合出しには協力したいのはやまやまなんです、けれども……
最近の不具合情報とか見てると今移行するのはまだちょっと危険な感じも。

現在のmaster serverを4.7のまま放置して、slave serverを4.8に移行していつでも戻せるようにしておこうかとも考えているのですが、万一その運用中にどちらかのハードが故障とか考えると、やっぱり気楽に移行するのは難しいかなあ、と悩み中です。

＞小林先生
コメントありがとうございます。
今後はAPIの拡張に注力していくということで把握しました。
CLAIMの未来は厳しそうという増田先生の意見に同意せざるを得ない状況ですね……。

**Comment by skoba** [comment]
CLAIMを発展的解消させていいのかどうかは，ORCA以外でDolphinと接続するレセコンとの接続が要求されるかどうかではないかと思います。現状でORCA以外にはあんまり選択肢なさそうなので，どうしたものかなと。
もし，CLAIM2を設計するとしたら，既存のCLAIMとは全く違うものになると思います。RESTベースで形式はJSON( or XML)だろうなぁ。

**Comment by MasudaNaika** [comment]
小林先生
>ORCA以外でDolphinと接続するレセコンとの接続
DolphinはORCAべったりなので、それ以外のレセコン接続はないと思います。
ORCA連携型電子カルテたちは、ORCAのCLAIMサポートがfade outならば、それに従うしか…
JSONかXMLかは、悩むところですが、各種プラットフォームで実装可能なように、固有のJSON parser依存にならないようにしないといけないと思ってます。Dolphinクライアント・サーバー間ではJackson nativeな機能を利用してObject to JSON, JSON to Object変換してラクしてますが。

**Comment by KatouBuntarou** [comment]
あまり他の電子カルテを分かっていない身で申し訳ないのですが・・・・・・。

正直な感想として、CLAIMを用いてORCAと連携している電子カルテ自体もしかして下火なのかしら、と少し思ってしまいました。
根拠は、我々が打ち上げるまでOSC側でのCLAIM関連のアクションがなかったように思われる、という点です。
電子カルテとのCLAIM通信不可であるバグなんて、連携機能のある電子カルテが広く用いられていればすぐに分かったと思います。

再起動直後にClaim通信不可となるバグが残っていた点についても、モジュールの修正量を見たところ数行程度のものでしたので、修正およびリリースの優先度は高くなかったのではないか、と思わずにいう気がしました。

何にせよHAORIに期待でしょうか……。
（そういえば今日ORCA-ANNOUNCEにて通達ありましたが、今年9月までにはORCA4.8に上げるのを余儀なくされるんですね……
http://www.orca.med.or.jp/news/2015-03_support.html）

**Comment by KunitoishiTomii** [comment]
＞CLAIM関連のアクションがなかった
素人の私は（えっ！テストは？）と思いましたが、プロの方々は意外と冷静なんでしょうか。
連携カルテは結構あるようなんです。きっと同じような問い合わせはあったに違いないと思いたいところです。

という自分もORCA4.6-4.7の時はテストしつつも、１０月にぎりぎりで移行・・その時は３ヶ月延長がありました。
いまアナウンスがあるということは、「早めにお願いします！延長はないから」ということでしょうね。

**Comment by MasudaNaika** [comment]
Katou san

＞連携機能のある電子カルテが広く用いられていれば
　私も同感でした。みなさんAPIに移行済みなんだと。ORCA USERS MLでも高知の黒岩先生がちょっと書かれてただけでした。ヒネてるのは私だけみたいです :-P

**Comment by HiroakiInomata** [comment]
はじめまして。
VMplayerに4.8のっけて、Dolphinとテストしているところです。
処方が引っ張ってこれない。。。

**Comment by KatouBuntarou** [comment]
＞HiroakiInomata先生

はじめまして。
環境が分からないので何とも言いかねますが、解決法が見つかることを願います。

**Comment by HiroakiInomata** [comment]
>KatouBuntarou様

なんとか解決しました。
わざわざコメントありがとうございます。
