### ISSUE TITLE
【EHRTouchA】 一部のラボデータが表示されない。

### ISSUE THREAD

**Issue by KatouBuntarou** [KatouBuntarou/OpenDolphin-2.3mh#85]
OpenDolphinからは参照可能なラボデータが、EHRTouchAでは表示されない現象が発生した。
（下図・同一患者のデータだが、EHRTouchA(上)とOpenDolphin(下)で表示されている項目に差異がある)
なお公開データを最低限にするために画像を一部削っています。
![ehrtoucha](https://cloud.githubusercontent.com/assets/3120581/7081718/e5a5e7cc-df81-11e4-991b-e6cc9efc511e.png)
![dolphin](https://cloud.githubusercontent.com/assets/3120581/7081720/e7153f22-df81-11e4-97e5-a2f8bd06e9c7.png)

発生頻度などまだ不明点多数。調査して情報が増えたらコメントに追記します。

**Comment by MasudaNaika** [comment]
日付の所からヘンですねぇ 1503300000となってる…
サーバー側で検査データをhtmlの表（テーブル）にしているのですが、まずはそれをチェックでしょうか。

**Comment by KatouBuntarou** [comment]
調査の結果、下記の事実が判明しました。

・日付情報に関しては、橋本医院オリジナルカスタマイズによるもので、
　DBに記録された文字列を日付の形に変換する処理を挟むことで対処可能。
・ラボデータが表示されない問題に関しては、LaboHtmlRenderer.javaのrender関数にて、value != null && value.getOut() == nullだった場合にはwriter.writeCharacters(value.getValue());を通すことにより現象改善を確認。
